# Generated by Django 3.2.8 on 2021-11-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='beers',
            field=models.ManyToManyField(to='beer.Beer'),
        ),
    ]
