# Generated by Django 3.2.8 on 2021-11-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_category_beers'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
