# Generated by Django 3.2.8 on 2021-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('beers', models.ManyToManyField(to='beer.Beer')),
                ('categories', models.ManyToManyField(to='beer.Category')),
            ],
        ),
    ]
